heat_template_version: 2014-10-16

description: >
  Amit Custom Script

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: firstboot_config}
      - config: {get_resource: amit_custom}

  firstboot_config:
    type: OS::Heat::SoftwareConfig
    properties:
      #group: script
      config: {get_file: firstboot-setup.sh}
      
  amit_custom:
    type: OS::Heat::SoftwareConfig
    properties:
      #group: script
      config: {get_file: amit-custom.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
