heat_template_version: 2014-10-16

description: >
  Amit Swap Script

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: amit-swap}

  amit-swap:
    type: OS::Heat::SoftwareConfig
    properties:
      #group: script
      config: {get_file: /home/stack/myosp10-templates/ospd-8-9-10-multiple-nic-vlan/amit-custom/amit-swap.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
