resource_registry:
  #OS::TripleO::BlockStorage::Net::SoftwareConfig: nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  #OS::TripleO::ObjectStorage::Net::SoftwareConfig: nic-configs/swift-storage.yaml
  #OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:

  ControlPlaneSubnetCidr: '24'
  EC2MetadataIp: 192.168.10.4
  ControlPlaneDefaultRoute: 192.168.10.254

  InternalApiNetCidr: 172.17.0.0/24
  #StorageNetCidr: 172.18.0.0/24
  #StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 192.16.20.0/24

  InternalApiNetworkVlanID: 20
  #StorageNetworkVlanID: 30
  #StorageMgmtNetworkVlanID: 40
  TenantNetworkVlanID: 50
  
  #ExternalNetworkVlanID: 20

  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  #StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  #StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  ExternalAllocationPools: [{'start': '192.168.20.10', 'end': '192.168.20.50'}]

  ExternalInterfaceDefaultRoute: 192.168.20.254

  DnsServers: ["8.8.8.8","8.8.4.4"]

  # Set to empty string to enable multiple external networks or VLANs
  #NeutronExternalNetworkBridge: "''"
  NeutronExternalNetworkBridge: "br-ex"

  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  #NeutronTunnelTypes: 'vxlan'
