# A Heat environment file which can be used to enable a
# a Neutron Nuage backend on the controller, configured via puppet
resource_registry:
  OS::TripleO::Services::NeutronL3Agent: OS::Heat::None
  OS::TripleO::Services::NeutronMetadataAgent: OS::Heat::None
  OS::TripleO::Services::NeutronOvsAgent: OS::Heat::None
  OS::TripleO::Services::ComputeNeutronOvsAgent: OS::Heat::None
  # Override the NeutronCorePlugin to use Nuage
  OS::TripleO::Services::NeutronCorePlugin: OS::TripleO::Services::NeutronCorePluginNuage
  OS::TripleO::Services::ComputeNeutronCorePlugin: ../puppet/services/neutron-compute-plugin-nuage.yaml

parameter_defaults:
  NeutronNuageOSControllerIp: '0.0.0.0'
  NeutronNuageNetPartitionName: 'default_name'
  NeutronNuageVSDIp: '0.0.0.0:0'
  NeutronNuageVSDUsername: 'username'
  NeutronNuageVSDPassword: 'password'
  NeutronNuageVSDOrganization: 'organization'
  NeutronNuageBaseURIVersion: 'default_uri_version'
  NeutronNuageCMSId: ''
  UseForwardedFor: true
  NeutronCorePlugin: 'nuage_neutron.plugins.nuage.plugin.NuagePlugin'
  NeutronEnableDHCPAgent: false
  NeutronServicePlugins: []
  NovaOVSBridge: 'alubr0'
  controllerExtraConfig:
    neutron::api_extensions_path: '/usr/lib/python2.7/site-packages/neutron/plugins/nuage/'
