heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config to configure VLANs for the
  controller role.
  
parameters:  
  ExternalIpSubnet:  
    default: ''  
    description: IP address/subnet on the external network  
    type: string  
  InternalApiIpSubnet:  
    default: ''  
    description: IP address/subnet on the internal API network  
    type: string  
  StorageIpSubnet:  
    default: ''  
    description: IP address/subnet on the storage network  
    type: string  
  StorageMgmtIpSubnet:  
    default: ''  
    description: IP address/subnet on the storage mgmt network  
    type: string  
  TenantIpSubnet:  
    default: ''  
    description: IP address/subnet on the tenant network  
    type: string  
  ExternalNetworkVlanID:  
    default: 10  
    description: Vlan ID for the external network traffic.  
    type: number  
  InternalApiNetworkVlanID:  
    default: 20  
    description: Vlan ID for the internal_api network traffic.  
    type: number  
  StorageNetworkVlanID:  
    default: 30  
    description: Vlan ID for the storage network traffic.  
    type: number  
  StorageMgmtNetworkVlanID:  
    default: 40  
    description: Vlan ID for the storage mgmt network traffic.  
    type: number  
  TenantNetworkVlanID:  
    default: 50  
    description: Vlan ID for the tenant network traffic.  
    type: number  
  ExternalInterfaceDefaultRoute:  
    default: '10.0.0.1'  
    description: default route for the external network  
    type: string  
  
  
resources:  
  OsNetConfigImpl:  
    type: OS::Heat::StructuredConfig  
    properties:  
      group: os-apply-config  
      config:  
        os_net_config:  
          network_config:  
            -  
              type: interface  
              name: nic3  
              use_dhcp: false  
              addresses:  
                -  
                 ip_netmask: {get_param: TenantIpSubnet}  
  
  
outputs:  
  OS::stack_id:  
    description: The OsNetConfigImpl resource.  
    value: {get_resource: OsNetConfigImpl}
