resource_registry:
  #OS::TripleO::BlockStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  #OS::TripleO::ObjectStorage::Net::SoftwareConfig: ../network/config/single-nic-vlans/swift-storage.yaml
  #OS::TripleO::CephStorage::Net::SoftwareConfig: nic-configs/ceph-storage.yaml

parameter_defaults:
  # Customize all these values to match the local environment
  InternalApiNetCidr: 172.17.0.0/24
  #StorageNetCidr: 172.18.0.0/24
  #StorageMgmtNetCidr: 172.19.0.0/24
  TenantNetCidr: 172.16.0.0/24
  ExternalNetCidr: 192.168.20.0/24
  
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: '24'
  
  InternalApiAllocationPools: [{'start': '172.17.0.10', 'end': '172.17.0.200'}]
  #StorageAllocationPools: [{'start': '172.18.0.10', 'end': '172.18.0.200'}]
  #StorageMgmtAllocationPools: [{'start': '172.19.0.10', 'end': '172.19.0.200'}]
  TenantAllocationPools: [{'start': '172.16.0.10', 'end': '172.16.0.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '192.168.20.100', 'end': '192.168.20.150'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 192.168.20.254

  
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.168.10.254
  EC2MetadataIp: 192.168.10.4  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  
  ControlPlaneDefaultRoute: 192.168.10.254
  
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 50
  #StorageNetworkVlanID: 300
  #StorageMgmtNetworkVlanID: 400
  TenantNetworkVlanID: 60
  ExternalNetworkVlanID: 70
  
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.122.1","8.8.8.8"]
  # May set to br-ex if using floating IPs only on native VLAN on bridge br-ex
  #NeutronExternalNetworkBridge: "''"
  NeutronExternalNetworkBridge: "br-ex"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  #NeutronTunnelTypes: ''
  # The tenant network type for Neutron (vlan or vxlan).
  #NeutronNetworkType: 'vxlan'
  # The OVS logical->physical bridge mappings to use.
  #NeutronBridgeMappings: 'datacentre:br-ex,tenant:br-provider'
  # The Neutron ML2 and OpenVSwitch vlan mapping range to support.
  #NeutronNetworkVLANRanges: 'tenant:100:200'
  #NeutronNetworkVLANRanges: 'datacentre:22:22,tenant:10:50'
  # Nova flavor to use.
  #OvercloudControlFlavor: baremetal
  #OvercloudComputeFlavor: baremetal
  # Number of nodes to deploy.
  #ControllerCount: 1
  #ComputeCount: 1

  # Sets overcloud nodes custom names
  # http://docs.openstack.org/developer/tripleo-docs/advanced_deployment/node_placement.html#custom-hostnames
  #ControllerHostnameFormat: 'controller-%index%'
  #ComputeHostnameFormat: 'compute-%index%'
  #CephStorageHostnameFormat: 'ceph-%index%'
  #ObjectStorageHostnameFormat: 'swift-%index%'
